///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StepsModelTopics {
/*
{
  "id": "1",
  "question_topic": "Intro"
}
*/

  String? id;
  String? questionTopic;

  StepsModelTopics({
    this.id,
    this.questionTopic,
  });
  StepsModelTopics.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    questionTopic = json['question_topic']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['question_topic'] = questionTopic;
    return data;
  }
}

class StepsModel {
/*
{
  "topics": [
    {
      "id": "1",
      "question_topic": "Intro"
    }
  ]
}
*/

  List<StepsModelTopics?>? topics;

  StepsModel({
    this.topics,
  });
  StepsModel.fromJson(Map<String, dynamic> json) {
    if (json['topics'] != null) {
      final v = json['topics'];
      final arr0 = <StepsModelTopics>[];
      v.forEach((v) {
        arr0.add(StepsModelTopics.fromJson(v));
      });
      topics = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (topics != null) {
      final v = topics;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['topics'] = arr0;
    }
    return data;
  }
}